### ISSUE TITLE
Create a docker image of the reporting plugin

### ISSUE THREAD

**Issue by Lawouach** [chaostoolkit/chaostoolkit-reporting#12]
Installing all the right dependencies for the reporting plugin can be cumbersome. Provide a docker image for this instead.

**Comment by russmiles** [comment]
Would the code for this issue be inside the <#C9P8UTJJK|kubernetes-job> project? Is that the plan.

**Comment by Lawouach** [comment]
I'd rather have a different image. The plugin dependencies could be massive so best keep a specific image for this and a lighter one for running experiments.

**Comment by russmiles** [comment]
Separate Docker file in this repo then perhaps? Or in a new repo entirely? I'm thinking of exploring this over lunch

**Comment by Lawouach** [comment]
Yeah, the Dockerfile should live here and dedicated only to the reporting :)

**Comment by palmerabollo** [comment]
I think this is fixed. There is already a [chaostoolkit/reporting](https://hub.docker.com/r/chaostoolkit/reporting/) image.

**Comment by Lawouach** [comment]
Agreed!
