### ISSUE TITLE
Create aggregated reports

### ISSUE THREAD

**Issue by palmerabollo** [chaostoolkit/chaostoolkit-reporting#16]
It would be useful to create aggregated reports, that is, reports generated using many journal files from different experiments.

I think that running many experiments is a common usage pattern and that `chaos run` and `chaos report` should be able to work with wildcards somehow.

Option 1:
- `chaos run --journal-path journal.json my/experiments/*.json`
- `chaos report --export-format=pdf journal.json journal.pdf`

Option 2:
- `chaos run --journal-path journal-1.json my-experiment-1.json`
- `chaos run --journal-path journal-2.json my-experiment-2.json`
- `chaos report --export-format=pdf journal*.json journal.pdf`

**Comment by russmiles** [comment]
Really like this idea!

**Comment by Lawouach** [comment]
Agreed. It shouldn't be too hard to implement.

**Comment by russmiles** [comment]
Would also like to make this part of adding: https://github.com/chaostoolkit/chaostoolkit/issues/81

The Contribution Model would really come into its own when it is part of a summarise contribution across a collection of experiment executions.
