### ISSUE TITLE
chaos report dependency error 

### ISSUE THREAD

**Issue by covetedfish** [chaostoolkit/chaostoolkit-reporting#24]
**Describe the bug**
Error in chaostoolkit-reporting mac installation steps listed [here](https://github.com/chaostoolkit/chaostoolkit-reporting/blob/master/osx-install.md); installation instructions for basictex incorrect

**Runtime versions**
Python 3.8.8
CLI                       1.9.0     
Core library        1.19.0    

**To Reproduce**
$ brew cask install basictex

**Expected behavior**
Installation of basictex

**Comment by CharlieMoon37** [comment]
Error fixed in PR #https://github.com/chaostoolkit/chaostoolkit-reporting/pull/27
